/**user**/
//login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
//register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
//register com
export const REGISTER_COM_SUCCESS = 'REGISTER_COM_SUCCESS'
export const REGISTER_COM_FAIL = 'REGISTER_COM_FAIL'

/**market**/
//list
export const MARKET_JOB_LIST_SUCCESS = 'MARKET_JOB_LIST_SUCCESS'
export const MARKET_JOB_LIST_FAIL = 'MARKET_JOB_LIST_FAIL'

//search 
export const MARKET_JOB_SEARCH_SUCCESS = 'MARKET_JOB_SEARCH_SUCCESS'
export const MARKET_JOB_SEARCH_FAIL = 'MARKET_JOB_SEARCH_FAIL'

/**jobDetail**/
export const LOAD_JOB_DETAIL_SUCCESS = 'LOAD_JOB_DETAIL_SUCCESS'
export const LOAD_JOB_DETAIL_FAIL = 'LOAD_JOB_DETAIL_FAIL'
